import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../components/Hero";
import PaymentSection from "../components/Payment";
import Footer from "../components/Footer";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Fudo - DAT Test Project</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Hero />

			<PaymentSection />

			<Footer />
		</div>
	);
};

export default Home;
