import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import Hero from "../components/Hero";

const PaymentSection = dynamic(() => import("../components/Payment"));
const Footer = dynamic(() => import("../components/Footer"));

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Fudo - DAT Test Project</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/** Hero Section Component */}
			<Hero />

			{/** Payment Section Component */}
			<PaymentSection />

			{/** Footer Section Component */}
			<Footer />
		</div>
	);
};

export default Home;
